### ISSUE TITLE
Cannot view databases that include a dot in their name.

### ISSUE THREAD

**Issue by alex-lawe** [fgeorges/expath-ml-console#15]
We receive a 404 when calling the first URL:

http://localhost:8010/db/Name.Test
http://localhost:8010/db/Name-Test

Since our naming convention is project.subproject most of our databases cannot be viewed with the EXPath Console Database view. Thanks a lot for your help and keep up the good work.

**Comment by fgeorges** [comment]
Hi Alex, thank you for your interest and for reporting this.

I've just pushed a fix, to allow dots in database and appserver names in URL.  The allowed characters were a bit too restrictive, and are now:

- `.`, `-`, `_` (dot, dash, underscore)
- `0-9`
- `a-z`, `A-Z`

The fix is in `master` and `develop`.  Can you try the latest version and see if it works for you as well?

**Comment by fgeorges** [comment]
BTW, if you are using the triple browser, you might be interested in the branch `feature/graphviz`, which contains improvements in that area (the above fix has been merged there as well).

This is **work in progress** though.  I try not to push commits until I am sure the codebase is OK, but hey, it's still work in progress :)

**Comment by alex-lawe** [comment]
Hi Florent, thank you very much for your fix. I can confirm that the fix works for new databases that have been created after pulling your changes. 

When I try to access:

http://localhost:8010/db/Name.Test

that was created before reporting this issue I receive a: 
 
SYSTEM ERROR (please report this to the mailing list): SEC-BADDB: xdmp:invoke-function(function() as item()*, <options xmlns="xdmp:eval"><database>1938277271580919227</database></options>) -- Specified database 1938277271580919227 is not allowed

I am not sure if this message is related to your changes since we haven't updated the EXPath console on any other machine yet.

We haven't used triples yet, but we will use them in a new project. Thanks.

**Comment by fgeorges** [comment]
Thank you for confirming it works! (well, at least in some cases...)

This one error is quite odd.  Can you send the complete stacktrace you should get on the same page, below the system error message?  And maybe as well the databases configuration in http://localhost:8010/tools/config (or `Tools` > `Admin entities`.)

For these 2 pieces of information, please double check they do not reveal any sensitive info (like the name of a database or a filename that would tell too much about your strategy to conquer the world.)

**Comment by alex-lawe** [comment]
Please find the requested information below:

[appservers.txt](https://github.com/fgeorges/expath-ml-console/files/2900019/appservers.txt)
[databases.txt](https://github.com/fgeorges/expath-ml-console/files/2900020/databases.txt)
[error.txt](https://github.com/fgeorges/expath-ml-console/files/2900021/error.txt)

**Comment by fgeorges** [comment]
Thanks.  This seems to be a security-related issue, and I see that the security database of `Name.Test` is `Documents`.  Looks like an error.  If it is, can you turn it back to `Schemas` and see if that solves the problem? (just go to the DB page in the admin console and select the right DB as its "schema database")

**Comment by alex-lawe** [comment]
Yes, that did the trick. Thank you so much. I was also wandering why your change regarding a rewrite rule would affect the database layer. My colleagues will be happy now to see the EXPath Console in production.

**Comment by fgeorges** [comment]
Good news!

Note that this is mostly a tool for development purposes.  You might keep in mind that in production (which usually means much more data) browsing lists of stuff might be very slow, especially:

- browsing all triples
- browsing "directories" with a lot of descendants (direct and indirect children)

Accessing a document, a "resource" (with an IRI or or a shorter CURIE), or a directory with reasonably few documents within, directly from the corresponding fields in the database page, all work fine regardless of the size of the database.  As well as browsing through the semantic graph by hoping from resource to resource.
