### ISSUE TITLE
Initialization of a fresh installation fails

### ISSUE THREAD

**Issue by alex-lawe** [fgeorges/expath-ml-console#16]
I tried to install the console on my new Developer licensed ML server:

1. git clone https://github.com/fgeorges/expath-ml-console.git
2. cd expath-ml-console
3. I edited credentials in xproject/mlenvs/dev.sjon
4. npm install mlproj -g
5. mlproj -e dev setup

After pressing the button at http://localhost:8010/init there is a:
500 Internal Server Error

JS-JAVASCRIPT: xdmp.dir(resp); -- Error running JavaScript request: TypeError: xdmp.dir is not a function
in /init/do-init.sjs, at 19:13, in get() [javascript]
in /init/do-init.sjs, at 128:16 [javascript]
in /init/do-init.sjs [javascript]

I am on a 18GB memory running Windows Server 2012 R2 Datacenter
with  MarkLogic Server 9.0-8.2 amd64 (normally I would use Linux)

**Comment by fgeorges** [comment]
Thank you for reporting this.  Good new is: this is a simple typo, it is fixed (you just need to pull the changes).

The bad news is: it happens in an error path (this is the exact statement that logs more info about the error), so you'd have to run it again and look at the logs to get more info about the original error (a HTTP GET request back at MarkLogic returned non-200, the logs will tell you what exactly).

Feel free to post the resulting error here if you need more help, or close the issue.

**Comment by hanshuebner** [comment]
I've run into this issue as well:
```
500 Internal Server Error
JS-JAVASCRIPT: xdmp.dir(resp); -- Error running JavaScript request: TypeError: xdmp.dir is not a function
in /init/do-init.sjs, at 19:13, in get() [javascript]
in /init/do-init.sjs, at 128:16 [javascript]
in /init/do-init.sjs [javascript]
```

**Comment by hanshuebner** [comment]
I tried finding the commit that is supposed to fix the issue, but it does not seem to be on the master branch.  Am I looking at the right branch?
