### ISSUE TITLE
How about adding the possibility of adding/editing/removing collections/properties and quality in the browser function?

### ISSUE THREAD

**Issue by peetkes** [fgeorges/expath-ml-console#2]
Hi,

I think it would make a nice addition to this great tool to be able to add/edit or delete things like collections, quality and properties   in the browser tool.

**Comment by fgeorges** [comment]
Hi @peetkes.  I am doing some digging and cleaning old issue tickets.  Just to mention this is indeed possible (and has been for quite a long time now) :-)
