### ISSUE TITLE
Support browsing document URIs not beginning with leading slash

### ISSUE THREAD

**Issue by willsthompson** [fgeorges/expath-ml-console#5]
I have many documents that do not begin with a leading slash as part of other URI naming conventions. It would be very convenient to be able to use the Browser tool to view and edit these documents as well.

**Comment by fgeorges** [comment]
That is indeed an improvement I think about.  I have a few ideas, but I am not quite sure I have nailed down what is the exact scope to support.  That would help to have more info about your naming standard.

Are the URIs "organized" (i.e. they somehow define a hierarchy, like with URIs of the form "/looks/like/dirs/and/files.xml"), or it's just a set of names?

Is it possible to identify the "roots" and how to browse through them to the next level?  E.g. in the current version, roots are "/" and everything of the form "http://xxx.xxx/".  Browsing the children of a given dir (including roots) is all the names up to the next "/' (e.g. given "/foo/" it's "/foo/bar/", "/foo/file.xml", etc.)  Different naming standards might lead to different rules (e..g the current rules do not support URNs, which would be great to browse in a "dir-like" way on ":" instead of "/").

Any idea welcome...

**Comment by willsthompson** [comment]
Hi Florent,

Sorry for the delay. Yes, they're organized using a dot-prefix like: .content-type/path/to/doc.xml. This is just a convention we came up with to associate multiple documents together via URI (like document properties fragments). We also use WebDav for some things, and we didn't want these types of documents to appear in that view, which is why the URIs start with a dot. 

So in my case the roots of all these documents begin with a dot. However, I realize this is completely specific to our implementation, so it might not help anyone else.

-W

**Comment by fgeorges** [comment]
Hi Will,

Sorry for the even longer delay.  The birth of my daughter got in the way somehow :-)  The good news is, I worked on a rewriting of the browser, to support, among other things, the URI scheme you described.  Basically, when browsing, every URI is associated with a "root" and a "path separator".  In your example, the root would be `.content-type/` (other typical roots would be `/`, `http://expath.org/` or `urn:sample:`).  The path separator would be `/` or `:` (or any other string that makes sense).

The branch `feature/browse` contains the corresponding code.  It is not ready yet for a release, but it is ready for early testing (and hopefully to let you browse your documents).

Any feedback welcome before I get a chance to ship it...

Regards.

**Comment by willsthompson** [comment]
Hi Florent,

No worries, and congratulations! I'll pull from the feature branch and test it.

Thanks,

Will

**Comment by fgeorges** [comment]
Hi Will.

If you want to test the newest developments on the browser, you can checkout the branch `feature/browse`.  It allows to configure less usual URI schemes in a config document.

Once updated, you can go to `Databases` in the menu, choose the database you want to browse, and at the bottom, in the section `Config`, you can create a config file automatically, which will contain config options commented out.  This should be enough to get you started.

You can use the following piece of the config file to browse the URI scheme you described above:

```
<scheme sep="/">
   <root>
      <start>.</start>
   </root>
   <regex match="1">(\.[^/]+/).*</regex>
</scheme>
```

**Comment by willsthompson** [comment]
Hi Florent,

This looks great. I'll pull down your updates this weekend.

**Comment by willsthompson** [comment]
Hi Florent,

I was able to dig into your updates this week and caught a few bugs...

The Config section's config.xml Create buttons throw an exception when clicked:

> XDMP-UNDFUN: (err:XPST0017) Undefined function t:config-uri-schemes() in /loader/insert-lib.xql, at 43:22, in i:absolute() [3.0]

So I tried manually inserting the config you gave me at the config URI for my database, but browsing throws an exception:

> XDMP-AS: (err:XPTY0004) $docs as element(c:config)\* -- Invalid coercion: fn:doc("http://expath.org/ml/console/config/Online.xml") as element(c:config)

It's a simple fix though, just a missing element selector after a doc() call on this line:

https://github.com/fgeorges/expath-ml-console/blob/feature/browse/src/database/db-config-lib.xql#L169

After that there were no hard errors, but the config I inserted doesn't have an effect on the URI scheme. This is the document I inserted at both `(Documents)http://expath.org/ml/console/config/Online.xml` and `(Online)http://expath.org/ml/console/config.xml`:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<c:config xmlns:c="http://expath.org/ns/ml/console">
  <uri-schemes>
    <scheme sep="/">
      <root>
      <start>.</start>
      </root>
      <regex match="1">(\.[^/]+/).*</regex>
    </scheme>
  </uri-schemes>
</c:config>
```

When I copy this scheme directly into the `$dbc:default-config` variable in `/src/database/db-config-lib.xql`, however, it works. I can't tell if this is a result of an error in the document I created, or if the document's config is getting excluded in the module somehow.

Hope that helps! Let me know if you have any questions about how I produced these issues, and I'll continue to pull down from `feature/browse` whenever I see new commits.

-Will

**Comment by fgeorges** [comment]
@willsthompson Note that the config document you quote above is wrong, it uses the prefix `c` for the Console namespace, and only the element `c:config` uses that prefix, all other elements are in no namespace (so the URI scheme config is never "seen" by the browsing engine).

The easiest fix is simply to remove the prefix `c` at all (like in the config doc created when you click on "Create it!" on a database page).

I've tested the feature and it works for me (at least on the latest branch, `project-environs`).  If you can confirm it works for you, I will take the opportunity to (finally) merge it to `develop` or even `master` now.

Thank you for your email to draw my attention on this ticket again :-)

**Comment by willsthompson** [comment]
@fgeorges I finally got around to upgrading to ML9 so I could test this, and I can confirm that it works. Thank you for staying on top of this feature!
